name: "ESLint Analysis"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: "20 5 * * 5"
  workflow_dispatch:

jobs:
  analyze:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout your code repository to scan
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"

      - name: Run npm i
        run: |
          npm i

      #- name: Run ESLint
      #  uses: thedave42/ghas-eslint-action@main
      #  with:
      #    src-dir: .

      - name: Run ESLint
        run: |
          ./node_modules/.bin/eslint -f @microsoft/eslint-formatter-sarif -o f1tv-dl-eslint.sarif . || exit 0
        # ./node_modules/.bin/eslint . || exit 0

      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: f1tv-dl-eslint.sarif

      - name: Upload sarif as artifact
        uses: actions/upload-artifact@v2
        with:
          name: f1tv-dl-eslint-results
          path: |
            !node_modules/**
            f1tv-dl-eslint.sarif
            
